# SPDX-License-Identifier: BSD-3-Clause
CONFIG_NRF_802154_RADIO_DRIVER=y
CONFIG_NRF_802154_SOURCE_NRFXLIB=y
CONFIG_NRF_802154_SL_OPENSOURCE=y
CONFIG_NRF_802154_RX_BUFFERS=4
CONFIG_NRF_802154_ENCRYPTION=n
CONFIG_NRF_802154_CARRIER_FUNCTIONS=n
CONFIG_ENTROPY_CC3XX=n
CONFIG_ENTROPY_NRF5_RNG=y
CONFIG_NRF_CC3XX_PLATFORM=n
CONFIG_HW_CC3XX=n
CONFIG_MPSL=n
CONFIG_BT=n
CONFIG_NETWORKING=n
CONFIG_IEEE802154=n
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_ASYNC_API=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_LOG=n
CONFIG_BOOT_BANNER=n
CONFIG_SHELL=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_USB_DEVICE_STACK=n
CONFIG_FLASH=n
CONFIG_NVS=n
CONFIG_SETTINGS=n
CONFIG_NFCT_PINS_AS_GPIOS=n
CONFIG_NRF_APPROTECT_USE_UICR=y
CONFIG_ZERO_LATENCY_IRQS=n
CONFIG_BOOTLOADER_MCUBOOT=n
CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_ISR_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=0
CONFIG_NEWLIB_LIBC=n
CONFIG_MINIMAL_LIBC=y
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_BUILD_OUTPUT_BIN=n
CONFIG_REBOOT=n
CONFIG_RESET_ON_FATAL_ERROR=n
