/* SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026, cc2530-zigbee contributors. See LICENSE.
 */
#ifndef MAC_LINK_DRIVER_H
#define MAC_LINK_DRIVER_H
#if !defined(CC2530_MAC_LINK) || !defined(CC2530_MAC_ADAPTER) || !defined(CC2530_MAC_RECONFIG)
#error mac_link_driver requires LINK, ADAPTER and RECONFIG
#endif
#include "bdb_join.h"
#include "mac_adapter.h"

typedef enum {
    MAC_LINK_DRIVER_OK = 0, MAC_LINK_DRIVER_WAIT, MAC_LINK_DRIVER_RANDOM,
    MAC_LINK_DRIVER_FINISHED, MAC_LINK_DRIVER_ARGUMENT, MAC_LINK_DRIVER_STATE,
    MAC_LINK_DRIVER_RADIO, MAC_LINK_DRIVER_CONSUMER, MAC_LINK_DRIVER_ORDER,
    MAC_LINK_DRIVER_COVERAGE
} mac_link_driver_result_t;

/* Caller-owned complete disjoint ordinary XDATA, including the BDB context,
 * its single interval owner, configuration and every driver object. No heap,
 * callback, ISR or reentrancy. No independent lower-service calls after bind.
 * Private compiler scratch is returning work, never persistent caller state.
 */
typedef struct {
    bdb_join_t MCU_XDATA *join;
    mac_tx_interval_t MCU_XDATA *owner;
    bdb_join_action_t action;
    bdb_join_action_t saved_action;
    bdb_join_event_t event;
    mac_tx_interval_action_t radio;
    mac_tx_interval_event_t source;
    radio_autoack_config_t config;
    mac_epoch_stamp_t clock, end;
    uint32_t now, rx_serial, closed_through, gaps, timeout, rx_ready_at;
    uint16_t limit, saved_short;
    uint8_t version, fault, adapter_result, consumer_result;
    uint8_t stage, random_wait, random_ready, random_byte;
} mac_link_driver_t;

/* Bind an already initialized real adapter, OFF after consumed close/drain,
 * to an already started SCANNING BDB owner. initial is the truthful installed
 * state (normal saved filter, RX off, unassociated short FFFF, BDB own IEEE).
 * Both scan and association saved states must describe this same snapshot.
 * init does not reset hardware or owners.
 * Driver storage must initially be zeroed; a bound object cannot be rebound.
 * Invalid arguments leave caller storage unchanged. Faults are retained:
 * fresh init is NOT recovery and the bound objects must not be recycled.
 */
mac_link_driver_result_t mac_link_driver_init(mac_link_driver_t MCU_XDATA * volatile ctx,
    bdb_join_t MCU_XDATA * volatile join, const radio_autoack_config_t MCU_XDATA * volatile initial,
    uint32_t timeout, uint16_t limit) JOIN_FAR;
/* Bounded foreground progress. RANDOM is a wait, not a generated byte.
 * Caller service gaps must stay below half the symbol epoch and meet the
 * consumers' existing time/work bounds. One outstanding delivery is processed
 * in rx_serial order and consumed with its exact token only after the consumer.
 * Every consumer now is floor(actual adapter observation), never ceil(now).
 * FINISHED means BDB is terminal, NOT that the driver is unbound or RX is off.
 * No automatic disposal/recovery/ownership transfer follows from that result.
 */
mac_link_driver_result_t mac_link_driver_step(mac_link_driver_t MCU_XDATA * volatile ctx) JOIN_FAR;
mac_link_driver_result_t mac_link_driver_random(mac_link_driver_t MCU_XDATA * volatile ctx,
    uint32_t generation, uint8_t retry, uint8_t nb, uint8_t qualified_byte) JOIN_FAR;

/* Composition policy:
 * scan uses KEEP_RAW after Beacon Request: software beacon-only dispatch,
 * no automatic ACK/pending extraction. OPENED is a new live observation of
 * that genuinely retained raw RX episode, rounded up only after actual time
 * reaches it; not a captured edge or a normal mac_adapter_open episode.
 * Association Request uses STOP_RX. POLL uses KEEP_AUTOACK; non-ACK frames
 * before normal handoff are a terminal local coverage error, not success.
 * Runtime unicast uses KEEP_AUTOACK; non-ACK TX uses STOP_RX then normal open.
 * gaps counts driver-initiated RX closures. OFF/configure/prepare intervals
 * never contribute coverage, including adapter-internal STOP_RX retirement.
 * CLOSED uses the latest event's real pre-stop watermark, including TX-only
 * RX_CLOSED/RETIRED from OFF (not just CLOSED_EVENT); restoration also waits
 * for owner IFS. INSTALL echoes the original epoch/token only after real open.
 * CRC is actual radio metadata, not syntax/authentication. Received DATA
 * reaches bdb_join_receive and its real crypto/NV owner. There is no secondary
 * RX packet queue: FULL is a retained local CONSUMER fault, with the original
 * adapter head and unexecuted grant intact, never an implicit packet drop.
 * Application send/confirm may be called between driver calls at ctx->now,
 * exclusively by this same foreground owner. No other BDB stepping is allowed.
 */
#endif
