/* SPDX-License-Identifier: BSD-3-Clause
 * Original public acceptance fixture, not a security/key-management service.
 */
#include "aes_fixture.h"

volatile MCU_XDATA aes_fixture_t aes_fixture_state;
MCU_XDATA uint8_t aes_fixture_key[16], aes_fixture_input[16], aes_fixture_output[18];
MCU_XDATA aes_fixture_work_t aes_fixture_work;
extern MCU_XDATA uint8_t aes_fault, aes_used;
extern volatile MCU_XDATA uint8_t aes_dma0[8], aes_dma1[32];
#define state aes_fixture_state
#define work aes_fixture_work

/* Five primary KATs, then sixteen original derived public cases; independently
 * regenerated by the host-only mathematical reference. Never an AES fallback.
 * SDCC string initializers retain their final NUL; only the first 48 bytes are data.
 */
const MCU_CODE uint8_t aes_fixture_vectors[21][49] = {
    "\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f\x00\x11\x22\x33\x44\x55\x66\x77\x88\x99\xaa\xbb\xcc\xdd\xee\xff\x69\xc4\xe0\xd8\x6a\x7b\x04\x30\xd8\xcd\xb7\x80\x70\xb4\xc5\x5a",
    "\x2b\x7e\x15\x16\x28\xae\xd2\xa6\xab\xf7\x15\x88\x09\xcf\x4f\x3c\x6b\xc1\xbe\xe2\x2e\x40\x9f\x96\xe9\x3d\x7e\x11\x73\x93\x17\x2a\x3a\xd7\x7b\xb4\x0d\x7a\x36\x60\xa8\x9e\xca\xf3\x24\x66\xef\x97",
    "\x2b\x7e\x15\x16\x28\xae\xd2\xa6\xab\xf7\x15\x88\x09\xcf\x4f\x3c\xae\x2d\x8a\x57\x1e\x03\xac\x9c\x9e\xb7\x6f\xac\x45\xaf\x8e\x51\xf5\xd3\xd5\x85\x03\xb9\x69\x9d\xe7\x85\x89\x5a\x96\xfd\xba\xaf",
    "\x2b\x7e\x15\x16\x28\xae\xd2\xa6\xab\xf7\x15\x88\x09\xcf\x4f\x3c\x30\xc8\x1c\x46\xa3\x5c\xe4\x11\xe5\xfb\xc1\x19\x1a\x0a\x52\xef\x43\xb1\xcd\x7f\x59\x8e\xce\x23\x88\x1b\x00\xe3\xed\x03\x06\x88",
    "\x2b\x7e\x15\x16\x28\xae\xd2\xa6\xab\xf7\x15\x88\x09\xcf\x4f\x3c\xf6\x9f\x24\x45\xdf\x4f\x9b\x17\xad\x2b\x41\x7b\xe6\x6c\x37\x10\x7b\x0c\x78\x5e\x27\xe8\xad\x3f\x82\x23\x20\x71\x04\x72\x5d\xd4",
    "\x00\x1f\x3e\x5d\x7c\x9b\xba\xd9\xf8\x17\x36\x55\x74\x93\xb2\xd1\xa7\xaa\xbd\x80\x93\xe6\xe9\xfc\xcf\xd2\x25\x28\x3b\x0e\x11\x64\x54\x53\x1e\x99\x17\xe9\xa0\xee\xd8\x91\x1e\x7c\x00\x33\xd2\x79",
    "\x13\x32\x51\x70\x8f\xae\xcd\xec\x0b\x2a\x49\x68\x87\xa6\xc5\xe4\x82\x95\x98\xeb\xfe\xc1\xd4\x27\x2a\x3d\x00\x13\x66\x69\x7c\x4f\x22\x33\xe3\xa4\xb5\xa3\xc6\x1a\xca\xa9\xae\x68\x18\x6c\x5e\x17",
    "\x26\x45\x64\x83\xa2\xc1\xe0\xff\x1e\x3d\x5c\x7b\x9a\xb9\xd8\xf7\xed\xf0\xc3\xd6\xd9\x2c\x3f\x02\x15\x18\x6b\x7e\x41\x54\xa7\xaa\xe6\x55\xfc\x81\x61\x1c\x1c\x05\x6b\x5b\x07\x77\x9e\xac\x15\x0c",
    "\x39\x58\x77\x96\xb5\xd4\xf3\x12\x31\x50\x6f\x8e\xad\xcc\xeb\x0a\xc8\xdb\x2e\x31\x04\x17\x1a\x6d\x70\x43\x56\x59\xac\xbf\x82\x95\x31\x77\xf9\xe7\x02\xde\x8c\x64\x81\x8a\xec\x40\x34\x54\xf1\x1e",
    "\x4c\x6b\x8a\xa9\xc8\xe7\x06\x25\x44\x63\x82\xa1\xc0\xdf\xfe\x1d\x33\x06\x09\x1c\x6f\x72\x45\x48\x5b\xae\xb1\x84\x97\x9a\xed\xf0\x66\xfb\xca\x30\xfe\x79\x50\xd4\xfb\x32\x5c\x3b\x37\xf9\x92\xfb",
    "\x5f\x7e\x9d\xbc\xdb\xfa\x19\x38\x57\x76\x95\xb4\xd3\xf2\x11\x30\x1e\x61\x74\x47\x4a\x5d\xa0\xb3\x86\x89\x9c\xef\xf2\xc5\xc8\xdb\xc5\x34\x13\x62\x54\x72\x64\xee\xf2\x98\xee\x72\xa6\x3f\x5b\x25",
    "\x72\x91\xb0\xcf\xee\x0d\x2c\x4b\x6a\x89\xa8\xc7\xe6\x05\x24\x43\x79\x4c\x5f\xa2\xb5\xb8\x8b\x9e\xe1\xf4\xc7\xca\xdd\x20\x33\x06\x4e\xa5\x6a\xa5\xc0\x34\xf3\x63\x6a\xff\x58\xcc\xf4\x74\x9e\xee",
    "\x85\xa4\xc3\xe2\x01\x20\x3f\x5e\x7d\x9c\xbb\xda\xf9\x18\x37\x56\xa4\xb7\xba\x8d\x90\xe3\xf6\xf9\xcc\xdf\x22\x35\x38\x0b\x1e\x61\x33\x55\x77\x80\x6a\xea\xcc\x53\x0b\x80\x8c\x76\xf3\x6b\x57\x49",
    "\x98\xb7\xd6\xf5\x14\x33\x52\x71\x90\xaf\xce\xed\x0c\x2b\x4a\x69\x8f\x92\xe5\xe8\xfb\xce\xd1\x24\x37\x3a\x0d\x10\x63\x76\x79\x4c\xa9\x1a\x90\xe6\x2d\x59\xdc\x32\xf6\xad\x27\x16\x93\xf4\x95\x44",
    "\xab\xca\xe9\x08\x27\x46\x65\x84\xa3\xc2\xe1\x00\x1f\x3e\x5d\x7c\xea\xfd\xc0\xd3\x26\x29\x3c\x0f\x12\x65\x68\x7b\x4e\x51\xa4\xb7\xf5\xe3\x32\x6c\x2c\xa0\x1c\x4c\x5b\xd8\x68\xb4\xf3\xe0\x1e\x13",
    "\xbe\xdd\xfc\x1b\x3a\x59\x78\x97\xb6\xd5\xf4\x13\x32\x51\x70\x8f\xd5\xd8\x2b\x3e\x01\x14\x67\x6a\x7d\x40\x53\xa6\xa9\xbc\x8f\x92\xdb\x44\xc5\xe4\xf8\x4b\x8e\xdd\x63\xd5\xc2\xb0\x58\xac\x4f\xe3",
    "\xd1\xf0\x0f\x2e\x4d\x6c\x8b\xaa\xc9\xe8\x07\x26\x45\x64\x83\xa2\x30\x03\x16\x19\x6c\x7f\x42\x55\x58\xab\xbe\x81\x94\xe7\xea\xfd\x87\xb1\x4b\x44\xe7\x68\x96\xeb\x1e\x50\x41\x67\xe4\xaa\x5b\x7f",
    "\xe4\x03\x22\x41\x60\x7f\x9e\xbd\xdc\xfb\x1a\x39\x58\x77\x96\xb5\x1b\x6e\x71\x44\x57\x5a\xad\xb0\x83\x96\x99\xec\xff\xc2\xd5\xd8\x2f\xb2\x01\x7b\x83\xb4\xf3\x12\x26\xa5\xee\x6b\xb0\xd3\x4d\xa9",
    "\xf7\x16\x35\x54\x73\x92\xb1\xd0\xef\x0e\x2d\x4c\x6b\x8a\xa9\xc8\x46\x49\x5c\xaf\xb2\x85\x88\x9b\xee\xf1\xc4\xd7\xda\x2d\x30\x03\x0d\x35\x11\xa8\x09\x51\x40\x85\x58\xd5\xa2\x34\x2b\x2a\x9c\x27",
    "\x0a\x29\x48\x67\x86\xa5\xc4\xe3\x02\x21\x40\x5f\x7e\x9d\xbc\xdb\xa1\xb4\x87\x8a\x9d\xe0\xf3\xc6\xc9\xdc\x2f\x32\x05\x08\x1b\x6e\x3d\x61\x2b\xb4\xcd\x77\x58\x53\xc6\xc3\x19\xa6\xec\xf0\x1f\xdf",
    "\x1d\x3c\x5b\x7a\x99\xb8\xd7\xf6\x15\x34\x53\x72\x91\xb0\xcf\xee\x8c\x9f\xe2\xf5\xf8\xcb\xde\x21\x34\x07\x0a\x1d\x60\x73\x46\x49\x61\x32\x6c\x0e\xb3\xe6\x16\x4c\xef\x45\x85\x2e\x1e\x86\x45\x99",
};

static void put16(volatile MCU_XDATA uint8_t *p, uint16_t n)
{
    p[0] = (uint8_t)n; p[1] = (uint8_t)(n >> 8);
}
static void put32(volatile MCU_XDATA uint8_t *p, uint32_t n)
{
    put16(p, (uint16_t)n); put16(p + 2, (uint16_t)(n >> 16));
}
static void serialize(void)
{
    if (state.kind == 1) {
        put32(state.diagnostic, work.clock.request.elapsed_ticks);
        put16(state.diagnostic + 4, work.clock.request.polls);
        state.diagnostic[6] = work.clock.request.timebase_status;
        put32(state.diagnostic + 7, work.clock.rollback.elapsed_ticks);
        put16(state.diagnostic + 11, work.clock.rollback.polls);
        state.diagnostic[13] = work.clock.rollback.timebase_status;
        state.diagnostic[14] = work.clock.saved_command;
        state.diagnostic[15] = work.clock.requested_command;
        state.diagnostic[16] = work.clock.observed_command;
        state.diagnostic[17] = work.clock.observed_status;
        state.diagnostic[18] = work.clock.rollback_result;
    } else {
        put32(state.diagnostic, work.aes.elapsed_ticks); put16(state.diagnostic + 4, work.aes.polls);
#define COPY(field, n) state.diagnostic[n] = work.aes.field
        COPY(timebase_status, 6); COPY(phase, 7); COPY(submitted, 8); COPY(input_complete, 9);
        COPY(output_drained, 10); COPY(published, 11); COPY(arms, 12); COPY(ack_issued, 13);
        COPY(dma_acked, 14); COPY(enc_ack_issued, 15); COPY(enc_acked, 16); COPY(sample_valid, 17); COPY(configured, 18);
#undef COPY
    }
}
static void cpu_snapshot(void)
{
    state.cpu_valid = 0;
    state.command = MMIO_READ(SOC_CLKCONCMD); state.status = MMIO_READ(SOC_CLKCONSTA);
    state.sleep = MMIO_READ(SOC_SLEEPCMD);
    state.enables[0] = MMIO_READ(SOC_IEN0); state.enables[1] = MMIO_READ(SOC_IEN1); state.enables[2] = MMIO_READ(SOC_IEN2);
    state.cpu_valid = 1;
}
static uint8_t cpu_ok(void)
{
    return state.cpu_valid && (state.command == 0xc9 || state.command == 0x88) && state.status == state.command &&
           state.sleep == state.initial_sleep && (state.sleep & 7u) == 4 &&
           !state.enables[0] && !state.enables[1] && !state.enables[2];
}
static uint8_t flag(uint8_t i)
{
    switch (i) {
    case 0: return MMIO_READ(AEF_IP0);
    case 1: return MMIO_READ(AEF_IP1);
    case 2: return MMIO_READ(AEF_TCON);
    case 3: return MMIO_READ(AEF_S1CON);
    case 4: return MMIO_READ(AEF_RFIRQF0);
    case 5: return MMIO_READ(AEF_RFIRQF1);
    case 6: return MMIO_READ(AEF_IRCON2);
    default: return MMIO_READ(SOC_RFERRF);
    }
}
static uint8_t idle(void)
{
    uint8_t i;
    uint16_t address;
    if (aes_fault || MMIO_READ(SOC_DMAARM) || MMIO_READ(SOC_DMAREQ) || MMIO_READ(SOC_DMAIRQ) ||
        MMIO_READ(SOC_IRCON) != state.initial_ircon || MMIO_READ(SOC_S0CON) != state.initial_enc ||
        MMIO_READ(SOC_ENCCS) != (aes_used ? 0x48 : 8)) return 0;
    address = aes_used ? MMIO_XADDRESS(aes_dma0) : 0;
    if (MMIO_READ(SOC_DMA0CFGL) != (uint8_t)address || MMIO_READ(SOC_DMA0CFGH) != (uint8_t)(address >> 8)) return 0;
    address = aes_used ? MMIO_XADDRESS(aes_dma1) : 0;
    if (MMIO_READ(SOC_DMA1CFGL) != (uint8_t)address || MMIO_READ(SOC_DMA1CFGH) != (uint8_t)(address >> 8)) return 0;
    for (i = 0; i < 8; i++) if (flag(i) != state.initial_flags[i]) return 0;
    return 1;
}
static void fault(uint8_t reason)
{
    state.reason = reason; state.phase = AEF_FAULT;
}
static void fill_buffers(void)
{
    uint8_t i;
    for (i = 0; i < 16; i++) {
        aes_fixture_key[i] = aes_fixture_vectors[state.vector][i];
        aes_fixture_input[i] = aes_fixture_vectors[state.vector][16u + i];
        aes_fixture_output[1u + i] = (uint8_t)~aes_fixture_vectors[state.vector][32u + i];
    }
    aes_fixture_output[0] = 0x69; aes_fixture_output[17] = 0x96;
}
static void verify_buffers(uint8_t success)
{
    uint8_t buffer, i, actual, expected;
    for (buffer = 0; buffer < 3; buffer++)
        for (i = 0; i < (buffer == 2 ? 18 : 16); i++) {
            if (buffer == 0) {
                actual = ((const volatile MCU_XDATA uint8_t *)aes_fixture_key)[i];
                expected = aes_fixture_vectors[state.vector][i];
            } else if (buffer == 1) {
                actual = ((const volatile MCU_XDATA uint8_t *)aes_fixture_input)[i];
                expected = aes_fixture_vectors[state.vector][16u + i];
            } else {
                actual = ((const volatile MCU_XDATA uint8_t *)aes_fixture_output)[i];
                expected = i == 0 ? 0x69 : i == 17 ? 0x96 : aes_fixture_vectors[state.vector][31u + i];
                if (!success && i && i != 17) expected = (uint8_t)~expected;
            }
            if (actual != expected) {
                state.mismatch_buffer = buffer; state.mismatch_index = i;
                state.actual = actual; state.expected = expected;
                if (state.phase != AEF_FAULT) fault(AEF_BYTES);
                return;
            }
            state.checked++;
        }
}
void aes_fixture_initialize(void)
{
    uint8_t i;
    bringup_initialize();
    for (i = 0; i < AEF_SIZE; i++) ((volatile MCU_XDATA uint8_t *)&state)[i] = 0;
    state.signature[0] = 'M'; state.signature[1] = '2'; state.signature[2] = 'A'; state.signature[3] = 'E';
    state.version = 2; state.size = AEF_SIZE; state.result = 255;
    state.mismatch_buffer = state.mismatch_index = 255; state.guards[0] = 0x69; state.guards[1] = 0x96;
    put16(state.timeout, (uint16_t)AEF_TIMEOUT); put16(state.limit, AEF_LIMIT);
    cpu_snapshot();
    state.initial_sleep = state.sleep;
    if (!cpu_ok() || state.command != 0xc9 || aes_used || aes_fault) { fault(AEF_ENTRY); return; }
    state.initial_ircon = MMIO_READ(SOC_IRCON); state.initial_enc = MMIO_READ(SOC_S0CON);
    for (i = 0; i < 8; i++) state.initial_flags[i] = flag(i);
    if ((state.initial_ircon & 1u) || (state.initial_enc & 3u) || !idle()) { fault(AEF_ENTRY); return; }
    state.phase = AEF_INIT;
}
#if defined(__SDCC)
static inline void aes_fixture_step(void)
#else
void aes_fixture_step(void)
#endif
{
    uint8_t i;
    const uint8_t *key, *input;
    if (state.phase == AEF_FAULT) return;
    if ((state.phase != AEF_INIT && state.phase != AEF_READY) || state.stage > AEF_CLOCK_RC) { fault(AEF_PHASE); return; }
    if (state.phase == AEF_READY) state.stage = state.stage == AEF_CLOCK_RC ? AEF_AES_RC : state.stage + 1u;
    state.phase = AEF_RUNNING; state.result = 255; state.checked = 0;
    state.kind = (state.stage == AEF_AES_RC || state.stage == AEF_AES_X) ? 2 : 1;
    for (i = 0; i < 19; i++) state.diagnostic[i] = 0;
    cpu_snapshot();
    if (!cpu_ok() || !idle()) { fault(AEF_INVARIANT); return; }
    for (i = 0; i < sizeof(work); i++) ((MCU_XDATA uint8_t *)&work)[i] = 0;
    if (state.kind == 2) {
        if (state.command != (state.stage == AEF_AES_RC ? 0xc9 : 0x88)) { fault(AEF_INVARIANT); return; }
        state.vector = state.completed % 21u;
        state.spaces = ((state.completed / 21u) + (state.stage == AEF_AES_X ? 1u : 0u)) & 3u;
        fill_buffers();
        /* SDCC's mixed-space ?: can lose the generic pointer tag. */
        if (state.spaces & 1u) key = aes_fixture_vectors[state.vector];
        else key = aes_fixture_key;
        if (state.spaces & 2u) input = aes_fixture_vectors[state.vector] + 16;
        else input = aes_fixture_input;
        state.result = aes128_encrypt_block(key, input, aes_fixture_output + 1, AEF_TIMEOUT, AEF_LIMIT, &work.aes);
        serialize(); state.fault_latch = aes_fault;
        state.cpu_valid = 0;
        if (state.result != AES_OK) { fault(AEF_AES_ERROR); verify_buffers(0); return; }
        if (work.aes.phase != 4 || work.aes.submitted != 7 || work.aes.input_complete != 7 ||
            !work.aes.output_drained || !work.aes.published || work.aes.configured != 3 || work.aes.arms != 4 ||
            work.aes.ack_issued != 3 || work.aes.dma_acked != 7 || work.aes.enc_ack_issued != 3 ||
            work.aes.enc_acked != 7 || work.aes.sample_valid != 3) { fault(AEF_INVARIANT); return; }
    } else {
        state.result = clock_select_init(state.stage == AEF_CLOCK_X ? CLOCK_XOSC32 : CLOCK_RC16,
                                         AEF_TIMEOUT, AEF_LIMIT, &work.clock);
        serialize(); state.cpu_valid = 0;
        if (state.result != CLOCK_OK) { fault(AEF_CLOCK_ERROR); return; }
    }
    cpu_snapshot();
    if (!cpu_ok() || state.command != (state.stage == AEF_CLOCK_X || state.stage == AEF_AES_X ? 0x88 : 0xc9) ||
        !idle()) { fault(AEF_INVARIANT); return; }
    if (state.kind == 2) {
        verify_buffers(1);
        if (state.phase == AEF_FAULT) return;
    }
    if (state.stage == AEF_CLOCK_RC) { state.completed++; bringup_tick(); }
    state.phase = AEF_READY;
}
#if defined(__SDCC)
void main(void)
{
    aes_fixture_initialize();
    if (state.phase == AEF_FAULT) aes_fixture_fault();
    aes_fixture_before();
    for (;;) {
        aes_fixture_step();
        if (state.phase == AEF_FAULT) aes_fixture_fault();
        aes_fixture_ready();
    }
}
#endif
